prevent PANIC when leader is None
happend in tests with tifs:
thread 'tokio-runtime-worker' panicked at /home/uli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tikv-client-0.3.0/src/pd/cluster.rs:270:47:
called `Option::unwrap()` on a `None` value